dist: xenial
language: node_js
node_js:
  - "8"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - binutils-mingw-w64-i686
      - binutils-mingw-w64-x86-64
      - gcc-7
      - gcc-mingw-w64-i686
      - gcc-mingw-w64-x86-64
      - mingw-w64
      - mingw-w64-tools
      - libstdc++-7-dev:amd64
      - libstdc++6:amd64
      - libstemmer0d:amd64
      - libstdc++6:i386
branches:
  only:
    - master
    - develop
    - travis
install:
  - npm install --save;
  - git clone https://github.com/emscripten-core/emsdk.git
  - ./emsdk/emsdk install latest && emsdk/emsdk activate latest && source emsdk/emsdk_env.sh
before_script:
  - npm rebuild node-sass
script: npm run build:dist

